remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: some test
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: some desc



