# 6 Introduktion (I) {#chap6}

\[10 sidor\]

I:et i akronymen IMRD står för \"introduktion\", vilket utgör en naturlig startpunkt i rapporteringen av ett vetenskapligt experiment. När man introducerar en experimentell studie brukar man inleda med en kort bakgrund av det aktuella forskningsläget och en motivering till den genomförda undersökningen. Det är viktigt att det i ett tidigt skede står klart för läsaren vilket forskningsproblem (eller \"kunskapsgap\") studien vill bidra till att undersöka och råda bot på. Genomgången av tidigare forskning ska leda fram till och motivera den aktuella studiens forskningsfrågor och hypoteser.

Inom samhällsvetenskapliga ämnen kan det vara intressant att undersöka hur mediepublikers attityder, kunskaper och beteenden påverkas av olika typer av interventioner, t.ex. en marknadsföringskampanj eller ett politiskt budskap. På samma sätt är det inom medicinska vetenskaper ofta av intresse att utröna om ett nytt läkemedel har någon positiv effekt på patienter jämfört med en kur bestående av verkningslösa sockerpiller. Ju mer mån man är att undersöka ett tillförlitligt kausalt samband mellan en behandling och tillståndet hos målgrupp, desto viktigare blir det att kunna genomföra ett kontrollerat experiment, där effekterna av en behandling systematiskt jämförs med effekterna av en annan behandling (eller ingen behandling alls).

Innan man genomför ett experiment är det dock viktigt att noga undersöka om liknande experiment redan genomförts i form av tidigare forskning. En sådan litteraturgenomgång visar ofta vilka mått och mätmetoder som använts inom samma område tidigare, samt vad man kan förvänta sig om man genomför ett nytt experiment inom ett liknande experimentellt paradigm (dvs. en ofta förekommande kombination av forskningsfrågor, experimentutföranden och mätmetoder). Alla dessa aspekter av hur en ny, planerad studie förhåller sig till tidigare forskning är viktiga genom hela forskningsprocessen. Tidigare använda mått och mätmetoder kan nämligen ge en god uppfattning om hur vi ska operationalisera våra forskningsfrågor till mätbara variabler (mer om detta strax). Tidigare uppnådda resultat, å andra sidan, genererar vissa förväntningar om vilka resultat vårt eget experiment kommer att leda till, vilket i sin tur hjälper oss att formulera motiverade hypoteser som är härledda från tidigare forskning inom området.

Inom flera samhällsvetenskapliga discipliner har den konstruktivistiska kunskapssynen haft en framträdande roll under de senaste decennierna (ref). Som en konsekvens av detta har det blivit viktigt att ange en så kallad teoretisk referensram i samband med att man introducerar en kvalitativ forskningsstudie. Denna samling av teoretiska perspektiv (t.ex. retorisk eller semiotisk teoribildning) har sedan en viktig funktion i när man som forskare analyserar sitt empiriska material genom att materialet tolkas med utgångspunkt i de teoretiska perspektiv man valt (därav den så kallade hermeneutiska forskningstraditionen). Inom den experimentella forskningen har kunskapssynen snarare beskrivits som positivistisk, och teoretiska perspektiv används för att göra förutsägelser eller prediktioner om numeriska samband som man förväntar sig att hitta i sina empiriska mätdata. Detta gör att teorier generellt sett spelar en annan roll inom ett positivistiskt experiment jämfört med en kvalitativ studie, i och med att i det förra fallet används empiriska resultat för att testa och eventuellt modifiera befintlig teoribildning. Se för övrigt kapitlet om vetenskapsteori i del 1.

