## 6.1 Forskningsfrågor

En viktig del av introduktionen till alla typer av vetenskapliga studier är att presentera studiens forskningsfrågor. En forskningsfråga ska på ett någorlunda enkelt och kortfattat sätt sammanfatta vilka frågeställningar som ett specifikt experiment adresserar. Därför är det förhållandevis accepterat att forskningsfrågor är något abstrakta och \"luddigt\" formulerade, så länge de är enkla, lättfattliga och kortfattade. Introduktionens vidare uppgift är nämligen att konkretisera studiens forskningsfrågor genom en process som kallas operationalisering, i vilken dessa forskningsfrågor omsätts till mätbara variabler som kan ingå i falsifierbara hypoteser. Man kan därför uttrycka det som att hypoteserna i en experimentell studie operationaliserar studiens forskningsfrågor. Operationalisering är ett mycket viktigt begrepp inom experimentell forskning, och vi återkommer mer utförligt till detta begrepp lite längre fram i detta kapitel, där vi också diskuterar hur detta begrepp hänger ihop med hypotesformulering.

Återgår vi till att diskutera begreppet forskningsfrågor mer generellt så finns det vissa tumregler som är viktiga att beakta. Den första tumregeln är att en forskningsfråga i någon del bör bygga på tidigare forskningsresultat, samt i någon del bör innehålla något nytt och outforskat. Med en sådan forskningsfråga kan man både upprepa (replikera) aspekter av tidigare forskning, men också utöka (extendera) tidigare forskning i syfte att skapa ny kunskap. En annan regel är att en forskningsfråga naturligtvis inte ska innehålla flera olika frågor, samt att två forskningsfrågor inte bör vara beroende av varandra (se övrig metodlitteratur, ref). Inom ramen för denna lärobok antar vi att en intressant forskningsfråga handlar om hur bildinnehållet i Facebook-poster påverkar läsarnas beteende och attityder. Närmare bestämt vill vi undersöka en upptäckt inom psykologisk forskning som visar att ett budskap upplevs som mer övertygande om det görs av en person som uppfattas som en auktoritet inom ett område (REF: Cialdini, 2001). Exempelvis kan vi föreslå att personen Leif GW Persson uppfattas som en auktoritet inom området kriminologi bland stora delar av den svenska mediepubliken. Vidare tänker vi oss att budskapet i en Facebook-post kan associeras med en auktoritetsperson genom att denna person visas i en bild som tillhör posten.

### 6.1.1 Planering av forskningsfrågor

I vårt tänkta experiment kretsar forskningsfrågorna kring effekterna av bildegenskaper hos Facebook-poster på internetanvändares visuella uppmärksamhet i samband med att de interagerar med dessa poster, samt effekter av bildinnehåll på användarnas självrapporterade nivå av upplevd trovärdighet hos samma poster. Tidigare forskning ger vid handen att självskattad (eller upplevd) trovärdighet i nyhetsartiklar oftast har uppmätts med hjälp av enkätfrågor där försöksdeltagaren får besvara frågor av typen \"Hur trovärdig var den nyhetsartikel du nyss läste?\", genom att välja ett svarsalternativ på en 7-gradig skala, där värdet 1 innebär \"Inte alls trovärdig\", värdet 4 innebär \"Varken trovärdig eller inte\", samt värdet 7 betyder \"Mycket trovärdig\". Tidigare ögonrörelseforskning visar att pupillens position på en datorskärm är en bra indikator på vilka objekt på en webbsida som användaren riktar sin visuella uppmärksamhet mot. Detta samband är mycket användbart i föreliggande experiment, och kommer att diskuteras mer ingående nedan. Forskningsfrågor bör vara ganska generellt formulerade, vilket gör att de ofta kan ha ett nära samband med studiens målsättningar.

### 6.1.2 Rapportering av forskningsfrågor

När man arbetar med ett manuskript för en artikel eller uppsats så formuleras ofta forskningsfrågorna som \"research questions\", vilket ibland förkortas RQ. En studie kan naturligtvis fokusera på flera relaterade forskningsfrågor, men det vanligaste är att man adresserar en eller två huvudfrågor, som sedan kan delas in ytterligare i underfrågor (RQ1a, osv). Vissa vetenskapliga tidskrifter har en mycket strikt tolkning av experimentell metod, vilket innebär att hypoteserna i ett så kallat naturligt experiment bara kan kallas forskningsfrågor. Exempel på formulerade forskningsfrågor med anknytning till bokens exempel-experiment. Således, i vårt tänkta experiment skulle den första forskningsfrågan kunna formuleras:

-   RQ1: Hur påverkar bildinnehållet i sociala medier-poster användarnas beteenden och attityder?

Som underfrågor till denna forskningsfråga skulle man kunna tänka sig \"RQ1a: Hur påverkar bildinnehållet i Facebook-poster läsarnas blickbeteende\", och \"RQ1b: Hur påverkar bildinnehållet i Facebook-poster läsarnas attityder gällande postens trovärdighet\".

