# 7 Metod (M) {#chap7}

\[60 sidor\]

En av de viktigaste aspekterna av experimentell forskning handlar om att resultaten av ett specifikt experiment måste kunna reproduceras eller replikeras av en eller flera oberoende forskare. Om resultaten av ett experiment inte kan reproduceras, tyder detta på en godtycklighet i genomförandet, och man kan då med rätta ifrågasätta det forskningsmässiga värdet av ett sådan experiment. Om resultaten av ett experiment inte kan upprepas så kan de heller inte jämföras med tidigare eller efterföljande studier inom samma forskningsområde. Det blir alltså omöjligt att bygga vidare på icke-reproducerbara resultat, och de resurser i form av tid och pengar man spenderat på att genomföra studien kan till största delen betraktas som bortkastade.

För att ge utomstående forskare (och i högsta grad, oss själva) en möjlighet att upprepa en forskningsstudie och förhoppningsvis erhålla liknande resultat, krävs en utförlig och standardiserad dokumentation av hur studien genomförts (Berger, 1977). Denna dokumentation kallas för studiens metod. Metoddelen av en forskningsrapport ska alltså kunna fungera som tillräckligt detaljerade instruktioner för att andra forskare ska kunna återskapa alla de viktigaste betingelserna under vilka vi erhöll våra egna forskningsresultat, t.ex. antal deltagare, mätinstrument, dataanalys, osv (APA-standard). Men experimentell metod handlar naturligtvis också om att praktiskt tillämpa vissa tillvägagångssätt som utvecklats för att vi ska kunna försäkra oss om att genomförande och resultat är så giltiga och tillförlitliga som möjligt (se definitioner ovan).

I denna lärobok har vi försökt täcka in dessa två olika men näraliggande betydelser av begreppet experimentell metod: dels som ett systematiskt och standardiserat sätt att i efterhand **rapportera** genomförandet av en studie, och dels som en uppsättning praktiska tillvägagångssätt som bör användas för att i förväg **planera** och därefter genomföra en experimentell studie. Således är detta kapitel av läroboken disponerat på ett sätt som ger oss möjlighet att i typisk turordning behandla de olika aspekter av experimentell metod som man som forskare förväntas kunna redovisa när man rapporterar sina resultat till en vetenskaplig tidskrift. Men inom varje metodaspekt kommer vi också att utförligt diskutera de olika experimentella tillvägagångssätt som är relevanta i samband med planering och genomförande av en forskningsstudie.

\- experimentell metod kan handla om att tänka baklänges, börja i hur resultaten rapporteras, och resonera sig fram till hur man ska planera studien

\- Ofta den första delen som skrivs när man rapporterar resultaten av en studie. Fördelaktigt att börja med en genomgång av hur studien faktiskt har genomförts.

\- kontrastera med metodologi, i del 1 ? Pedagogiskt att presentera efterföljande text som tre centrala beståndsdelar: 1) deltagare, 2) mätinstrument, och 3) experimentella villkor/manipulationer.

