## 7.5 Experimentell design  {#sec7.5}

\[10 sidor\]

Design är ett ganska svårdefinierat begrepp, vars innebörd handlar om att på ett överskådligt sätt sammanfatta strukturen och planen hos en vetenskaplig undersökning (på svenska används ibland \"upplägg\" eller \"planering\" som synonymer till design). Man kan säga att begreppet experimentell design har två centrala aspekter: den första är kopplad till att beskriva och specificera de beroende och oberoende variablerna som ingår en undersökning, medan den andra centrala aspekten är kopplad till att beskriva hur deltagarna i en undersökning exponeras för de experimentella villkor som omfattas av de oberoende variablerna (dvs hur behandlingar eller \"trials\" är distribuerade inom en experimentell studie). I det följande ska vi börja med att diskutera experimentell design i relation till oberoende variabler, vilka vi även refererar till som behandlingsvariabler i denna bok.

För att få en bättre förståelse av begreppet experimentdesign börjar vi med ett exempel från den medicinska forskningen. En epidemiologisk forskare bestämmer sig för att testa ett nytt vaccin som den tagit fram. För att undersöka detta bestämmer sig forskaren (i vanlig ordning :) för att rekrytera försöksdeltagare som delas in i två grupper, där en grupp får en overksam spruta med saltvattenlösning, och deltagare i den andra gruppen får en spruta med det nya vaccinet. Vi säger därför att detta experiment har en **mellangruppsdesign**, eftersom effekten av den oberoende variabeln (vatten vs. vaccin) mäts och jämförs mellan två likvärdiga grupper av deltagare. Som tumregel kan man säga att en enklare experimentdesign är ofta att föredra framför en mer komplicerad design. Orsaken till detta är att en enkel design ofta genererar tydligare resultat som är enklare att tolka. Enklare experimentella designer består ofta bara av en enda oberoende variabel som kan vara antingen kontinuerlig eller diskret (). När man designar ett experiment försöker man ofta passa på att

Även om enkla experiment är idealet så finns det flera situationer där exempelvis en mellangruppsdesign inte riktigt räcker till. En sådan situation kan inträffa om den uppmätta effekten av en behandling på en viss utfallsvariabel är relativt liten jämfört med kontrollvillkoret. I sådana situationer riskerar alltså en eventuell effekt av behandlingen att drunkna i bakgrundsbruset från andra orsaksfaktorer. En annan situation där en enkel mellangruppsdesign kan vara otillräckligt är om det naturligt förekommer stora individuella skillnader mellan deltagarna inom respektive försöksgrupp med avseende på utfallsvariabeln. Gemensamt för båda dessa problematiska situationer är alltså att den förväntade effekten av behandlingen är liten i relation till andra omgivande bruskällor (i överförd bemärkelse används ibland det engelska uttrycket \"low signal-to-noise ratio\"), och att det därför föreligger en risk för typ I- och typ II-fel (false positives respektive false negatives).

Just detta är ofta fallet i samhällsvetenskapliga undersökningar, där det är vanligt att kvantitativa data samlas in genom självrapporterade enkätsvar som ytterst är beroende av varje deltagares vilja och förmåga att svara uppriktigt, vilket skapar stor individuell variation. Här krävs alltså experimentdesigner som är mer robusta i på grund av brusiga datainsamlingar innehållande flera potentiella felkällor. En lösning på detta problem är så kallad **inomgruppsdesign**, vilket vi ska diskutera längre fram i detta kapitel. Den tydligaste skillnaden gentemot mellangruppsdesign är dock att denna typ av experiment exponerar varje deltagare för både kontrollvillkor och behandlingsvillkor, samt att denna exponering kan upprepas flera gånger för varje deltagare. Av naturliga skäl är detta experimentella upplägg många gånger svårt eller omöjligt att genomföra inom den medicinska forskningen, eftersom försöksdeltagare inte både kan ges en placebotablett och en verksam medicin vid samma tillfälle.

### 7.5.1 Instruktioner och uppgifter {#sub7.5.1}

Många samhällsvetenskapliga experiment brukar börja med en instruktion som ges till varje deltagare för att förklara vad som kommer hända, vilken uppgift som ska lösas, samt vad vi som forskare mäter hos deltagaren (dock nämner vi inte vad som har manipulerats i experimentets, eftersom deltagaren bör hållas omedveten om detta). Dessa instruktioner är i sig en viktig aspekt av experimentet, eftersom forskaren därigenom försöker uppnå en standardiserad situation där alla deltagare uppfattar experimentet på samma sätt, för att på så sätt öka validiteten och reliabiliteten hos insamlade data.

Men vi skulle också kunna använda instruktioner för att ge olika uppgifter till två grupper av deltagare, medan resten av experimentet är identiskt för båda grupperna, och i så fall utgör själva uppgiften experimentets manipulation. Låt oss ta ett konkret exempel i form av en undersökning där varje deltagare får titta på ett antal bilder som visas en i taget på en datorskärm samtidigt som vi spelar in deltagarens blickbeteende. Hälften av deltagarna får instruktionen att titta fritt på bilderna (\"free-viewing\"), medan den andra hälften får instruktionen att försöka hitta ett specifikt objekt i varje bild (\"visual search\"). Genom denna variation i instruktioner har vi skapat ett experiment med mellangruppsdesign, innehållande ett kontrollvillkor (titta fritt), samt ett behandlingsvillkor (hitta objekt). Vi kan därefter undersöka om blickbeteende mellan dessa grupper systematiskt skiljer sig åt på det sätt vi antagit i våra hypoteser.

Exemplet ovan handlar om en specifik användning av instruktioner för att generera ett experimentellt villkor. Mer generellt kan man säga att det ofta är fördelaktigt att ge deltagare någon form av uppgift i samband med ett experiment, eftersom man därigenom minskar variationen i hur deltagare interagerar med experimentets villkor. Mindre variation gör i sin tur att vi får större möjligheter att upptäcka statistiska skillnader mellan villkoren med avseende på någon utfallsvariabel. En uppgift av något slag gör deltagarna mer fokuserade. Dessutom innebär en uppgiftsstyrd eller målorienterad experimentdesign (engelska \"task-oriented\" eller \"goal-directed\") att vi som forskare får möjlighet att mäta uppgiftsprestation (engelska \"task performance\"), vilket ofta är en användbar variabel.

### 7.5.2 Randomisering och balansering {#sub7.5.2}

Vi har hittills diskuterat de individer som deltar i experiment (7.2 Försöksdeltagare), de beroende variabler experimentet undersöker hos deltagarna (7.3 Mätinstrument), samt de behandlingar som dessa individer genomgår (7.4 Experimentella villkor). När vi nu fortsätter med att diskutera experimentdesign (7.5), är förmodligen en av de viktigaste aspekterna begreppet \"randomisering\" (ref, Fisher). Randomisering är så centralt att det ibland tas för givet inom den experimentella forskningen. Dock kan detta utgöra ett av de mer krävande momenten i att designa ett experiment för studenter och yngre forskare, eftersom randomisering ofta kräver grundläggande kunskaper i programmering för att realiseras. Bristfällig randomisering i experimentdesignen är ofta något som skapar problem när man analyserar effekten av experimentella villkor på en eller flera utfallsvariabler, och försöker dra slutsatser om statistiskt säkerställda effekter.

Randomisering (på engelska \"random assignment\") innebär i grund och botten att experimentledaren låter slumpen avgöra vilket experimentellt villkor (eller behandling) varje deltagare genomgår. I det enklaste fallet, där experimentet endast består av ett kontrollvillkor samt ett behandlingsvillkor, kan vi tänka oss att experimentledare låter varje deltagare singla slant, och beroende på utfallet (krona eller klave) tilldelar deltagaren ett av de två villkoren. Med tillräckligt många deltagare förutsäger slumpens lagar att fördelningen mellan två experimentella villkor kommer bli ungefär 50%, dvs. att hälften av deltagarna exponeras för kontrollvillkoret, och den andra hälften genomgår behandlingsvillkoret. Det viktigaste syftet med randomisering är dock att försäkra oss om att experimentledaren inte kan påverka experimentets genomförande, och att varje deltagare tilldelas ett villkor på ett sätt som är oberoende av vilket villkor alla andra deltagare tilldelas.

Dessutom kan randomiseringen användas för att hålla försöksdeltagaren i ovisshet om vilket behandlingsvillkor den exponerats för. Denna experimentdesign är vanlig i medicinska studier, och kallas då för en blind-studie (på engelska \"blinded experiment\"), dvs. varje försöksdeltagare hålls omedveten om den får ett sockerpiller (kontrollvillkor) eller en verksam substans (behandlingsvillkor). Tanken med denna design är att reducera effekten av deltagarens förväntningar, den så kallade placebo-effekten, för att därigenom erhålla mer tillförlitliga resultat. Inom den medicinska forskningen är det också vanligt att gå ett steg längre, och därigenom även hålla försöksledaren omedveten om vilken behandling en viss deltagare tilldelas. I sådana fall talar man om en dubbel blind-studie (på engelska \"double-blind study\"). Tanken med att hålla försöksdeltagaren omedveten om vilket experimentellt villkor den exponeras för, är besläktad med tanken att hålla deltagaren omedveten eller \"naiv\" om syftet med experimentet, dvs. vilka mätvariabler och behandlingsvariabler som används inom experimentet (jfr. 7.2.4). Gemensamt för dessa designprinciper är syftet att reducera bias och öka tillförlitligheten hos studien.

Återgår vi till att diskutera randomisering mer specifikt, så kan vi konstatera att denna designprincip är ganska enkel och intuitiv så länge en studie bara kontrasterar två villkor, och där varje deltagare endast exponeras för ett av dessa villkor en gång. Denna så kallade mellangruppsdesign (vilken vi diskuterar mer utförligt i nästa avsnitt) fungerar ofta bra för enkla studier, men inom samhällsvetenskap och humanvetenskap kan det ibland krävas något mer avancerade experimentdesigner, vilket i sin tur kräver andra former av randomisering. Detta kan exempelvis inträffa om experimentet innefattar ett kontrollvillkor och två eller flera behandlingsvillkor, eller om varje deltagare genomgår flera villkor, eller om experimentet innehåller någon kombination av dessa situationer. Betänk experimentdesignen som visas i tabellen nedan, där varje deltager genomgår kontrollvillkoret samt två olika behandlingsvillkor.

Tabell 1.1 Det här är tabellrubriken

  Deltagare        Stimulus 1     Stimulus 2     Stimulus 3     
  ---------------- -------------- -------------- -------------- --
  Deltagare 1 \>   Kontroll       Behandling A   Behandling B   
  Deltagare 2 \>   Behandling A   Kontroll       Behandling B   
  Deltagare 3 \>   Behandling B   Behandling A   Kontroll       
  \...                                                          

I denna situation skulle vi som forskare kunna välja att låta varje deltagare först genomgå villkoret Kontroll, följt av Behandling A och Behandling B. Denna design vore kanske den enklaste att implementera, men den kan vara problematisk på andra sätt. För att konkretisera denna situation kan vi tänka oss ett experiment där varje deltagare får betrakta tre ansiktsbilder i följd. Den första bilden visar ett ansikte med neutral min (Kontroll), medan det andra ansiktet visar en ledsen min (Behandling A), och det tredje ansiktet visar en glad min (Behandling B). För varje ansikte försöksdeltagaren får betrakta, instrueras den att ange på en skala hur glad eller ledsen personen på bilden är. Skalan går från mycket ledsen (-10) till mycket glad (+10).

Problemet med denna experimentdesign, där villkoren inte randomiseras, inträffar om vi tänker oss att varje villkor i någon grad influerar nästkommande villkor (jfr. begreppet \"priming\"). Detta skulle kunna inträffa om deltagarna, efter att ha betraktat det neutrala ansiktet, upplever att det ledsna ansiktet är något mindre ledset än om det ledsna ansiktet hade betraktats först. På samma sätt skulle deltagarna kunna uppleva att det glada ansiktet är något mindre glatt efter att de betraktat det ledsna ansiktet. Denna typ av systematiska ordningseffekter (på engelska \"order effects\") är svåra att undvika helt, men med hjälp av randomisering kan vi åtminstone försöka minimera dem.

I ansiktsstudien ovan skulle vi kunna lösa randomiseringen på åtminstone två olika sätt. Det första sättet vore att ge varje bild 1/3 chans att presenteras som första, andra och tredje villkor. Detta kallas för randomisering utan ersättning (\"randomization without replacement\"). Det andra sättet vore att göra en lista med alla de sex möjliga ordningsföljder i vilka man kan presentera tre villkor, och sedan presentera villkoren enligt dessa ordningsföljder för de sex första deltagarna. Därefter upprepas ordningsföljderna för nästa sex deltagare. Denna metod kallas för \"latin square\", och innebär idealiskt att vi skulle behöva ett totalt antal deltagare i studien som är en multipel av sex (dvs. 12, 18, 24, osv.) för att designen ska vara helt balanserad. Randomisering är alltså viktigt om man kan misstänka att experimentella villkor skapar ordningseffekter, vilket som regel antas vara fallet i humanvetenskapliga och samhällsvetenskapliga studier. Mest kritiskt i studier med inomgruppsdesign och upprepade villkor.

### 7.5.3 Mellangruppsdesign {#sub7.5.3}

Den enklaste formen av experimentell design (och därmed ofta den tydligaste) kan antagligen härledas från den medicinska forskningen. I denna experimentdesign ingår två stycken grupper av försöksdeltagare som i möjligaste mån är jämförbara (eller \"matchade\") vad gäller ett antal olika demografiska variabler, såsom ålder, kön och hälsotillstånd mm. Varje deltagargrupp blir sedan slumpmässigt tilldelad en behandling (t.ex. en ny blodtryckssänkande medicin som testas) eller ingen behandling (t.ex. ett sockerpiller som antas vara verkningslöst). Efter att varje försöksdeltagare genomgått en av dessa två behandlingar (eller experimentella villkor) undersöker experimentledaren effekten av respektive behandling genom att uppmäta värdet på en utfallsvariabel kopplad till deltagaren (t.ex. blodtryck). Om den medicinska behandlingen haft en effekt jämfört med sockerpiller bör man finna en tydlig kontrast mellan deltagargrupperna (t.ex. lägre genomsnittligt blodtryck).

Ett typisk kommunikationsvetenskapligt exemplet på mellangruppsdesign är ett så kallat AB-test. Expandera.

Tabell 1.1 Det här är tabellrubriken

  Tabellhuvud    Tabellhuvud   Tabellhuvud                   
  -------------- ------------- -------------- -------------- --
  Villkor \>     Kontroll      Behandling A   Behandling B   
  Deltagare \>   Deltagare 1   Deltagare 2    Deltagare 3    
  \...           Deltagare 4   Deltagare 5    Deltagare 6    

Låt oss i det följande återvända till vårt tänka exempel-experiment, där syftet är att undersöka hur medieanvändares interaktion med (ögonrörelsemätning), och attityder till (survey-skalor), Facebook-poster påverkas av om posten innehåller en bild på en auktoritetperson alternativt en bild på en neutral person. För att testa detta experimentellt behöver vi först välja ut en Facebook-post som vi kan använda som stimuli. Vi kan anta att vi väljer ut en post på temat brottlighet i Sverige. Därefter behöver vi välja två bilder som kommer utgöra experimentets behandlingar eller villkor. Vi antar att kriminologen Leif G.W. Persson kan anses vara en auktoritetsperson inom området brottslighet, och använder en bild på honom för att konstruera Facebook-postens behandlingsvillkor. Därefter väljer vi en bild på en neutral person, och använder denna bild för att konstruera vårt kontrollvillkor.

Om vi nu skulle välja att genomföra detta experiment med mellangruppsdesign, skulle det innebära att vi började rekrytera ett hundratal försökspersoner som är någorlunda lika i demografiskt avseende, och någorlunda representativa för den population vi ämnar undersöka. Därefter skulle vi låta deltagarna interagera med Facebook-posten på en datorskärm medan vi spelade in deras ögonrörelser, och efter att ha läst posten skulle deltagarna få markera på en 7-gradig likert-skala hur pass trovärdig de upplevde att Facebook-posten i sin helhet var. Hälften av deltagarna skulle därvidlag få läsa posten i kontrollvillkoret, medan den andra häften fick läsa posten i behandlingsvillkoret. Randomiseringen skulle kunna lösas så att villkoren slumpades fram med 50% sannolikhet vardera, eller genom att varannan deltagare genomgick kontrollvillkoret, och varannan behandlingsvillkoret.

\- ibland enda möjliga design, introducerar dock mätfel på grund av individuella skillnader, dvs deltagargrupperna kan aldrig bli helt \"matchade\" i alla avseenden - En deltagargrupp per villkor (between-subjects design) \"oberoende grupper\" - upprepade behandlingar (repeated measures) omvandlar studien till inomgruppsdesign - effekten kontrasteras mellan deltagare - två behandlingar + kontroll, kräver fler deltagare, dvs designen skalar inte upp så bra - övergång till nästa avsnitt: sammanfatta svagheterna med mellangruppsdesign

### 7.5.4 Inomgruppsdesign {#sub7.5.4}

Ett sätt att åtgärda en del av svagheterna med mellangruppsdesign är att istället använda experiment med inomgruppsdesign, ibland även kallat inompersonsdesign, eller på engelska \"within-subjects design\". Det främsta kännetecknet för denna experimentdesign är att varje deltagare ingår i studiens alla villkor, både kontrollvillkor och experimentella villkor. Detta innebär således att varje försöksdeltagare jämförs med sig själv mellan undersökningens villkor. En betydande fördel med en sådan experimentdesign är att man därigenom kan kontrollera för individuella skillnader mellan deltagare, och att effekten av denna bruskälla därför blir mindre när man kontrasterar mätningar av någon responsvariabel mellan experimentella villkor (variansen inom varje villkor blir mindre). Man kan således argumentera för att en inomgruppsdesign är mer rättvis än en mellangruppsdesign i och med att varje deltagare exponeras för alla manipulationer som undersökningen består av. Detta kan vara fördelaktigt ur etisk synpunkt. En annan fördel med denna design är att den skalar upp bättre om man skulle tillföra fler nivåer på en oberoende variabel, dvs. om man skulle lägga till en behandling. I sådana situationer behöver man inte rekrytera en grupp med nya försöksdeltagare (vilket vore fallet i en mellangruppsdesign), utan samma deltagare exponeras bara för ytterligare ett behandlingsvillkor. En möjlig nackdel med detta är att experimentet tar längre tid för varje deltagare, när den ska delta i fler villkor.

\- effekten kontrasteras inom varje deltagare, dvs inga deltagargrupper - Alla deltagare genomgår alla villkor (within-subjects design) \"beroende grupper\", inompersonsdesign - lämpligare vid beteendevetenskapliga studier - variables and level of variables (e.g. 2x3 between-subjects design) - Något om Blandad design (mixed design).

Tabell 1.1 Det här är tabellrubriken

  Tabellhuvud    Tabellhuvud   Tabellhuvud                   
  -------------- ------------- -------------- -------------- --
  Villkor \>     Kontroll      Behandling A   Behandling B   
  Deltagare \>   Deltagare 1   Deltagare 1    Deltagare 1    
  \...           Deltagare 2   Deltagare 2    Deltagare 2    

Diskutera expempel experiment med Facebook-poster enligt ett upplägg med inomgruppsdesign.

### 7.5.5 Upprepade villkor {#sub7.5.5}

När vi i föregående avsnitt diskuterat mellangruppsdesign och inomgruppsdesign har vi avstått från att ta upp frågan om upprepade villkor. Underförstått har vi då antagit att varje deltagare exponeras för ett villkor (mellangruppsdesign) eller alla villkor (inomgruppsdesign) endast en gång. I vissa typer av experiment är detta ett rimligt antagande; i medicinska studier förväntar vi oss kanske att varje deltagare genomgår ett kontrollvillkor i form av sockerpiller, eller ett experimentellt villkor i form av ett läkemedel, endast en gång. Man skulle dock kunna tänka sig att dessa behandlingar upprepas ett antal gånger med samma försöksdeltagare och med en viss tidsperiods mellanrum. Tanken med att upprepa villkoren är att de uppmätta resultaten sammantaget ska ge en mer rättvis bild av effekten hos varje deltagare än om endast en mätning gjordes. I sådana fall skulle man kalla detta för

\- formuleringen \"within-subjects repeated measures design\"

Tabell 1.1 Det här är tabellrubriken

  Tabellhuvud      Tabellhuvud   Tabellhuvud                   
  ---------------- ------------- -------------- -------------- --
  Deltagare 1 \>   Kontroll      Behandling A   Behandling B   
  Deltagare 1 \>   Kontroll      Behandling A   Behandling B   
  Deltagare 2 \>   Kontroll      Behandling A   Behandling B   
  \...                                                         

Diskutera expempel experiment med Facebook-poster enligt ett upplägg med mellangruppsdesign och upprepade villkor.

### 7.5.6 Faktoriell design {#sub7.5.6}

Två eller fler oberoende variabler (faktorer), med två eller fler diskreta nivåer (eng. \"levels\") på varje faktor. 3x2 faktoriell design. Tillåter att effekten av alla nivåer på varje enskild faktor testas, liksom effekten av alla kombinationer av faktorer (interaktioner). Används ofta inom naturvetenskapliga sammanhang, t.ex. materialtestning. \"Fully crossed design\" - variables and level of variables (e.g. 2x3 between-subjects design)

Tabell 7.5.5 Faktoriell experimentdesign

  Tabellhuvud         Tabellhuvud         Tabellhuvud                             
  ------------------- ------------------- ------------------- ------------------- --
                      Faktor A (nivå 0)   Faktor A (nivå 1)   Faktor A (nivå 2)   
  Faktor B (nivå 0)   Kontroll A0/B0      Behandling A1/B0    Behandling A2/B0    
  Faktor B (nivå 1)   Behandling A0/B1    Behandling A1/B1    Behandling A2/B1    

### 7.5.7 Kvasi-experimentell design {#sub7.5.7}

T.ex. undersökning av effekterna av medborgarlön? Kontrastera med naturliga experiment? Ett sätt att tänka kring oberoende variabler är att de representerar experimentets utfallsvariabler. En annan faktor som har stor betydelse i samband med urvalet av.. lacks random assignment, naturliga exp del 1

### 7.5.8 Planering av experimentell design {#sub7.5.8}

Håll designen så enkel som möjligt för att underlätta tolkningen av resultat. Helst inte mer än 2x2 design. - diskutera utifrån exempel-experiment med bildinnehåll hos Facebook-poster

bild kommer ovan

### 7.5.9 Rapportering av experimentell design {#sub7.5.9}

Håll designen så enkel som möjligt för att underlätta tolkningen av resultat. Helst inte mer än 2x2 design.

