# Efterarbete {#chap08}
[08-0-wc-file]: <> 7  34 253 rmd-08-0-Efterarbete.md7  32 230 rmd-08-0-Efterarbete.md
[08-0-comment]: <> (10 sidor)

Denna text kommer är tänkt att ersätta sektion 08 resultat och 09 diskussion. Därmed frångår boken den tidigare indelningen enligt IMRD.


## Resultat (R) {#sec08.1}

\[5 sidor\]

Här hänvisar vi främst läsaren till befintlig litteratur inom statistiska metoder

Liksom i det föregående metodkapitlet, kommer vi detta kapitel

\- prediction vs. fitting (meningsfulla modeller kan vara viktigare än prediktion, retro-fitting hypotheses).

### Deskriptiv statistik {#sub08.1.1}

Här kommer lite Brödtext igen. Här ko

Lägg noga märke till var skiljetecken satts ut, var det ska vara kursiv stil etc. Vid engelska titlar ändras *and* till *och* eller *&, in* til

### Inferentiell statistik {#sub08.1.2}

Här kommer nåt om causal inference. In statistical hypothesis testing a type I error is the rejection of a true null hypothesis (also known as a \"false positive\" finding or conclusion), while a type II error is the non-rejection of a false null hypothesis (also known as a \"false negative\" finding or conclusion

\[1\]). Much of statistical theory revolves around the minimization of one or both of these errors, though the complete elimination of either is a statistical impossibility for non-deterministic algorithms.

### Presentation av statistik {#sub08.1.3}

Här kommer något om diagram och visualiseringar.




## Diskussion (D) {#sec08.2}

\[5 sidor\]

Här skulle man kunna använda sig av en domstolsmetafor. Den experimentella studien är genomförd och nu står insamlat material och experimentdesign åtalad för att visa något. Bevis, evidens, circumstantial evidence, alias. Forskaren antar både rollen som åklagare och försvarsadvokat (noll-hypotes). Kan läggas i 8.1 också.

Vi skulle kunna tänka oss ett experiment som inte involverar mänskliga försöksdeltagare. T.ex. en webbplats genomgår (\"behandlas\") med två olika typer av sökoptimeringsstrategier. Därefter undersöker vi hur båda sidor indexeras och listas bland googles sökresultat. Den beroende responsvariabeln är rankning (page rank), lägre värden innebär mer positivt utfall. Testet kan upprepas i flera trials.

### Hypoteser och empiriska resultat {#sub08.2.1}

Relatera faktiska observationer till ursprungliga förväntade hypoteser. Här kommer lite Brödtext igen. Här ko

### Alternativa förklaringar till resultat {#sub08.2.2}

Lägg noga märke till var skiljetecken satts ut, var det ska vara kursiv stil etc. Vid engelska titlar ändras *and* till *och* eller *&, in* til

### Framtida forskning {#sub08.2.3}

Hkommer lite Brödtext igen. Här kommer lite Brödtext igen. Här kommer lite Brödtext igen.



