# 7 Genomförande {#chap07}
[07-0-comment]: <> (60 sidor)

En av de viktigaste aspekterna av experimentell forskning handlar om att resultaten av ett specifikt experiment måste kunna reproduceras eller replikeras av en eller flera oberoende forskare. Om resultaten av ett experiment inte kan reproduceras, tyder detta på en godtycklighet i genomförandet, och man kan då med rätta ifrågasätta det forskningsmässiga värdet av ett sådan experiment. Om resultaten av ett experiment inte kan upprepas så kan de heller inte jämföras med tidigare eller efterföljande studier inom samma forskningsområde. Det blir alltså omöjligt att bygga vidare på icke-reproducerbara resultat, och de resurser i form av tid och pengar man spenderat på att genomföra studien kan till största delen betraktas som bortkastade.

För att ge utomstående forskare (och i högsta grad, oss själva) en möjlighet att upprepa en forskningsstudie och förhoppningsvis erhålla liknande resultat, krävs en utförlig och standardiserad dokumentation av hur studien genomförts (Berger, 1977). Denna dokumentation kallas för studiens metod. Metoddelen av en forskningsrapport ska alltså kunna fungera som tillräckligt detaljerade instruktioner för att andra forskare ska kunna återskapa alla de viktigaste betingelserna under vilka vi erhöll våra egna forskningsresultat, t.ex. antal deltagare, mätinstrument, dataanalys, osv (APA-standard). Men experimentell metod handlar naturligtvis också om att praktiskt tillämpa vissa tillvägagångssätt som utvecklats för att vi ska kunna försäkra oss om att genomförande och resultat är så giltiga och tillförlitliga som möjligt (se definitioner ovan).

I denna lärobok har vi försökt täcka in dessa två olika men näraliggande betydelser av begreppet experimentell metod: dels som ett systematiskt och standardiserat sätt att i efterhand **rapportera** genomförandet av en studie, och dels som en uppsättning praktiska tillvägagångssätt som bör användas för att i förväg **planera** och därefter genomföra en experimentell studie. Således är detta kapitel av läroboken disponerat på ett sätt som ger oss möjlighet att i typisk turordning behandla de olika aspekter av experimentell metod som man som forskare förväntas kunna redovisa när man rapporterar sina resultat till en vetenskaplig tidskrift. Men inom varje metodaspekt kommer vi också att utförligt diskutera de olika experimentella tillvägagångssätt som är relevanta i samband med planering och genomförande av en forskningsstudie.

\- experimentell metod kan handla om att tänka baklänges, börja i hur resultaten rapporteras, och resonera sig fram till hur man ska planera studien

\- Ofta den första delen som skrivs när man rapporterar resultaten av en studie. Fördelaktigt att börja med en genomgång av hur studien faktiskt har genomförts.

\- kontrastera med metodologi, i del 1 ? Pedagogiskt att presentera efterföljande text som tre centrala beståndsdelar: 1) deltagare, 2) mätinstrument, och 3) experimentella villkor/manipulationer.

## 7.1 Pilottest  {#sec7.1}

\[5 sidor\]

Innan man genomför ett skarpt experiment, vilket ofta kräver mycket resurser I form av tid och arbete, är det klokt att genomföra experimentet i liten skala. På så vis kan man I tidigt stadium fånga upp problem med experimentdesignen. Testa validitet och reliabilitet. Intervjua deltagare efter. Iterativ process. Det är ofta en fördel att kunna rapportera ett pilottest eller en förstudie i samband med att sakkunniga forskare granskar och bedömer om det är lämpligt att publicera resultaten i en tidskrift.

## 7.2 Försöksdeltagare  {#sec7.2}

\[10 sidor\]

De individer som deltar i en studie kallades tidigare kort och gott \"subjekt\" (på engelska \"subjects\"). På senare tid har man vänt sig emot detta något avhumaniserande språkbruk och istället antagit den generella termen \"deltagare\". Här använder vi ibland beteckningen "försökspersoner" eller \"försöksdeltagare\" för att ytterligare betona den experimentella forskningens användning av kontrasterande behandlingar, villkor eller \"försök\" för att studera dess effekter på deltagarna (på engelska kallas sådana upprepade försök oftast för \"trials\", vilket är ett viktigt begrepp inom området experimentdesign som diskuteras längre fram i detta kapitel).

### 7.2.1 Representativt urval {#sub7.2.1}

Inom samhällsvetenskapliga forskningsområden är det vanligt att anta att deltagarna i en studie ska vara så representativa som möjligt i förhållande till en viss målpopulation. Tanken bakom detta är att man av praktiska skäl bara har möjlighet att inkludera en mindre grupp deltagare i en studie (t.ex. studenter på ett visst utbildningsprogram), och utifrån detta begränsade urval vill man sedan kunna generalisera undersökningens resultat till en större grupp människor (t.ex. alla universitetsstuderande i Sverige). Även om detta resonemang i grund och botten är rimligt, är det främst användbart inom större enkätstudier som syftar till att undersöka attityder, kunskaper och beteenden hos en avgränsad och väldefinierad population av individer. Ett annat vanligt exempel på enkätundersökning där deltagarnas representativitet är avgörande är politiska opinionsundersökningar. Utifrån drygt tusen deltagare vill man här kunna generalisera till hela Sveriges befolkning med relativt låg felmarginal.

\- ska vi ta upp termer som "obundet slumpmässig urval", stratifierat urval, bekvämlighetsurval, snöbollsurval (inom intervjustudier)?

### 7.2.2 Demografiska egenskaper {#sub7.2.2}

Inom experimentell forskning tenderar man att tänka lite annorlunda kring frågan om att erhålla ett representativt urval av försöksdeltagare till en studie. Det är framför allt två saker som föranleder detta. För det första är det vanligt att man använder sig av objektiva och mätbara observationer i ett experiment, till skillnad från subjektiva (självrapporterade) och kvalitativa observationer i en survey, vilket antas leda till lägre nivåer av brus i de mätningar som genomförs. För det andra är det vanligt att de experimentella effekter man studerar är så små och svåra att uppmäta, att alltför stora individuella skillnader hos deltagarna riskerar att generera så mycket brus att effekten av en behandling inte kan detekteras. Av dessa två skäl är det vanligt att man eftersträvar någorlunda homogena deltagargrupper när man syftar till att genomföra experimentella studier.

Att man delvis frångår principen om representativt urval inom experimentell metodik har alltså att göra med att man på olika sätt vill begränsa mängden slumpartade och systematiska mätfel, dvs brus. Detta är ett tänk som kommer från det naturvetenskapliga området signalbehandling (ref). Nackdelen med detta förfarande är naturligtvis att generaliserbarheten riskerar att minska, vilket oftast är en svaghet. Inom vissa utbildningssystem där deltagande i experimentella studier är obligatoriskt för studenter, har den experimentella forskningen kritiserats för att endast kunna generalisera till just den befolkningsgrupp som studenter vanligtvis tillhör, t.ex. 18-25-åringar med västerländskt ursprung och förhållandevis god socioekonomisk ställning (ref). Referera till begreppen bakgrundsvariabler, kontrollvariabler.

En annan faktor som har stor betydelse i samband med urvalet av försöksdeltagare är naturligtvis om de forskningsfrågor man undersöker är kopplade till någon specifik befolkningsgrupp, t.ex. vad gäller ålder (barn eller äldre), språk (enspråkiga eller flerspråkiga) och kognition (funktionsnedsatta och normalbefolkning). Om så är fallet, blir det ju naturligt att rekrytera deltagare från just dessa grupper och därmed ge avkall på möjligheten att kunna generalisera sina resultat till en bredare population. I viss mån styrs alltså urvalet av försöksdeltagare av den tidigare forskning som vi med vårt experiment vill bygga vidare på och kontribuera till. Som en tumregel kan man dock säga att en experimentell studie brukar bygga på 20-100 deltagare, där åldersspannet inte är för stort, och könsfördelningen inte är för skev. Längre fram i detta kapitel kommer vi även att diskutera hur experimentdesign påverkar antalet deltagare som är lämpligt i en studie.

### 7.2.3 Etiska hänsynstaganden {#sub7.2.3}

En internationell trend inom samhällsvetenskaplig forskning som gjort sig gällande under senare år är att stor vikt läggs vid forskarens etiska hänsyn gentemot dess försöksdeltagare. Exempelvis kan en journal kräva att ett experiment genomgått en etisk prövning innan det genomförs, i annat fall vill tidskriften inte publicera resultaten. Detta är naturligtvis i grunden en positiv utveckling, men det adderar ofta ett administrativt moment som behöver klaras av innan en studie kan sättas i verket. När en etisk kommitté utvärderar ett experiment är det framför allt två aspekter man tar hänsyn till: 1) att deltagaren inte ska lida några men i samband med genomförandet av undersökningen, och 2) att forskaren har en genomtänkt plan för hantering av forskningsdata som samlas in. Ett exempel på den första aspekten är analysera vilka villkor och manipulationer som förekommer, samt om mätutrustningen är invasiv eller inte. Exempel på det andra hänsynstagandet är att försöksdeltagares personliga integritet inte ska bli lidande (t.ex. känsliga personuppgifter), samt att forskningsdata ska hanteras på ett säkert sätt som även tillåter deltagaren att begära ut sina uppgifter i efterhand. Som regel är dessa hänsyn viktigare för anställda forskare; för studentprojekt brukar inte etisk prövning av studier vara nödvändigt.

### 7.2.4 Planering av deltagare {#sub7.2.4}

Här kommer några praktiska råd i samband med att man rekryterar försöksdeltagare till en experimentell studie. För det första, underskatta inte betydelsen av att få tillgång till motiverade personer som dels är omedvetna om syftet med experimentet, och dels är någorlunda representativa för den grupp av människor resultaten ska kunna generaliseras till. För det andra, underskatta inte den tid och möda som krävs för att lösa de logistiska aspekterna av att låta ett hundratal(?) individer genomgå de behandlingar som ett experiment består av under kontrollerade och likartade förutsättningar. Både bland forskare och studenter finns en föreställning om att planering av försöksdeltagare löser sig självt; så är dock inte fallet.

Redan på ett tidigt stadium är det viktigt att fastställa om det planerade experimentet är av en sådan art att det kräver etisk prövning, och i så fall måste studien godkännas av en etisk nämnd innan rekrytering av deltagare påbörjas. Etisk prövning blir ofta aktuellt om känsliga personuppgifter eller biometriska data samlas in, och om invasiv försöksutrustning som på något sätt kan förväntas påverka deltagaren används. I vårt exempel-experiment uppfylls inte dessa kriterier, eftersom tanken är att manipulera bildinnehåll i Facebook-poster, samt samla in data om deltagarnas blickbeteende och attityder.

Förutsatt att inga etiska hinder föreligger, kan rekryteringen av försöksdeltagare påbörjas genom att förslagsvis annonsera om studien och förse intresserade personer med kontaktuppgifter till försöksledaren (epost, telefonnummer, webblänk), samt möjlighet för presumtiva deltagare att ange dag och tid när de har möjlighet att delta. För att öka chanserna att folk ska anmäla sig till undersökningen kan det vara fördelaktigt att erbjuda någon form av ersättning, t.ex. en biobiljett eller en lunchkupong, dock underlättar det om ersättningsnivån inte överstiga ca 100 kr eftersom det då blir beskattningsbar inkomst.

I praktiken är det dock kanske viktigare att prata med tilltänkta försöksdeltagare och göra dem intresserade av forskningen och motiverade att avsätta tid för deltagande. Denna information måste då vägas mot att deltagarna ska vara omedvetna om syftet med det tilltänkta experimentet. Utgår vi återigen från vårt exempel-experiment, innebär detta att vi kan informera om att studien undersöker Facebook-användning, men att vi undanhåller hur vi manipulerat bildinnehållet i Facebookposterna (auktoritetspersoner gentemot neutrala personer). På forskningsjargong innebär detta att deltagarna avsiktligt hålls omedvetna eller \"naiva\" om studiens behandlingar, och att detta i sin tur minskar risken för påverkan eller \"bias\" i de observationer som samlas in.

Om vi förflyttar oss framåt i tiden till själva genomförandet av studien, så är det viktigt att betänka att varje försöksdeltagare ska ha rätt att ge informerat samtycke till studien innan den deltar (den engelska termen för detta är \"informed consent\"). Om deltagaren är yngre än 15 år krävs **dessutom** alla vårdnadshavares samtycke. Detta innebär att försöksledarna i förväg har en informationssida som beskriver forskarens respektive deltagarens rätt- och skyldigheter. Detta dokument ska undertecknas av deltagaren innan experimentet påbörjas.

Forskaren har rätt att: använda insamlade data för publikationer

Forskaren är skyldig att: beskriva mätutrustning, t.ex. att en ögonrörelsemätare kommer mäta pupillens position i relation till datorskärmen.. beskriva vilka data som samlas in och generellt syfte.. förvara data säkert

Deltagaren har rätt att: få sina data utlämnade (raderade om ingen anonymisering)

Deltagaren är skyldig att: Signera att ersättning tagits emot

### 7.2.5 Rapportering av deltagare {#sub7.2.5}

När man väl genomfört studien och är i färd med att rapportera vilka personer som deltagit så krävs det vanligtvis betydligt mindre arbete än i planerings- och genomförandefasen. I artikeltexten läggs information om experimentets försöksdeltagare ofta som den första underrubriken till metodstycket, och det är också därför vi tar upp försöksdeltagare på just detta ställe i läroboken. Anledningen till att vi använder denna så kallade IMRD-disposition är det skapar en kronologisk struktur för både planering och rapportering av vetenskapliga studier, och för de som vill genomföra ett experiment kan det vara värdefullt att bekanta sig med denna konvention.

\- demografiska variabler, medelålder, range

\- exempel på hur detta skulle kunna formuleras i ett manuskript, på engelska?

\- representativt urval, population, bakgrundsvariabler, individuell variation

\- bortfall, missing cases

## 7.3 Mätinstrument  {#sec7.3}

\[10 sidor\]

I en experimentell studie är det avgörande att införliva mätinstrument som på ett giltigt och tillförlitligt sätt kan uppmäta effekten av en behandling på en eller flera responsvariabler. En viktig anledning till att experiment och mätinstrument är nära förknippade, är att denna typ av positivistisk forskning syftar till att försöka säkerställa en faktisk skillnad mellan olika grupper av deltagare och olika typer av behandlingar, vilket till syvende och sist kräver analys med hjälp av statistiska metoder. Det räcker alltså inte med att forskaren rapporterar en subjektivt upplevd skillnad mellan försöksgrupper; denna skillnad måste bevisas!

I detta sammanhang bör mätinstrument uppfattas som ett relativt abstrakt begrepp; det kan röra sig om medicinsk eller fysiologisk mätutrustning, men i många samhällsvetenskapliga ämnen handlar mätinstrument ofta om enkätfrågor där svarsalternativen är utformade som Likert-skalor, exempelvis med skalsteg från 1-7. Med hjälp av ett sådant survey-instrument tänker man sig att det går att uppmäta försöksdeltagarnas attityder kring något ämne. Men man skulle också kunna tänka sig ett experiment inom marknadsföring som använder en binär mätvariabel. I detta fall skulle två deltagargrupper kanske titta på varsin version av en reklamfilm, och sedan svara \"ja\" eller \"nej\" på frågan om de var intresserade av att köpa den produkt som marknadsfördes i båda filmerna.

I det hypotetiska experiment som vi resonerar om i denna bok används två olika mätinstrument för att registrera olika typer av responser hos deltagarna i samband med att de tittar på Facebook-poster med bilder föreställande auktoritetspersoner respektive neutrala eller okända personer. I första steget används en ögonrörelsemätare för att mäta hur försöksdeltagarna visuella uppmärksamhet fördelar sig över Facebook-posten, och sedan används en 7-gradig Likert-skala för att mäta hur bildinnehållet påverkat deras attityder angående postens trovärdighet. De hypoteser som antagits för detta experiment är att auktoritetspersoner kommer att orsaka en ökning av visuell uppmärksamhet (dvs. hur länge deltagarna tittar på bilden), samt en ökning av upplevd trovärdighet hos posten (dvs. hur höga värden som väljs på Likert-skalan). En viktig skillnad mellan dessa två mätinstrument är att ögonrörelsemätning fångar ett objektivt beteende hos deltagaren, medan Likert-skalor registrerar mer subjektiva responser som rapporteras av deltagaren själv. Denna skillnad utvecklas lite mer i det följande.

### 7.3.1 Mätning av subjektiva responser {#sub7.3.1}

Survey-frågor + svarsalternativ, likertskalor, attityder, beroende variabler. Självrapportering. Intervjusvar. Potentiellt problem med validitet, reliabilitet. Hänvisa till litteratur om enkätundersökningar, t.ex. Trost. Dessutom använder vi surveyfrågor med likertskalor för att mäta hur läsarna skattar artiklarnas trovärdighet. Implementeras som t.ex. Google forms. Diskutera validitet. Objektiva eller självrapporterade mätningar

### 7.3.2 Mätning av objektiva responser {#sub7.3.2}

I det tänkta experiment som ligger till grund för denna bok, använder vi oss huvudsakligen av två mätinstrument. Vi använder en så kallad ögonrörelsemätare (på engelska \"eye-tracker\") för att göra objektiva och kontinuerliga mätningar av hur läsarnas visuella uppmärksamhet fördelar sig över ytan på de Facebook-artiklar vi använder som stimuli i studien (se 2.2.5 nedan). Fysiologiska och beteendevetenskapliga, (mer) objektiva responser. Potentiellt bättre validitet, reliabilitet. Tillvägagångssätt, planering. Reaktionstider. Viljestyrda eller autonoma, reflexiva. Pupilldilatation eller visuell uppmärksamhet. Top-down och bottom-up

### 7.3.3 Beroende variabler {#sub7.3.3}

Syftar generellt till att uppmäta och registrera en respons på ett stimuli eller en behandling, därför säger man ibland att syftet med mätinstrumenten är att på ett giltigt och tillförlitligt sätt mäta en responsvariabel. Ofta kontinuerlig eller binär (logistisk regression), men kan också vara multinomial eller kategorisk. Survey-frågor, svarsalternativ, likertskalor, attityder. \"Beror\" av en kronologiskt föregående orsak, dvs. behandling. På engelska kallas detta \"dependent variable\". Beroende variabler kallas ibland också mätvariabler eller utfallsvariabler. Jämför med oberoende variabler, förklaringsvariabler, experimentella villkor, behandlingar i nästa stycke av boken. På engelska \"independent variable\".

### 7.3.4 Planering av mätinstrument {#sub7.3.4}

Tillvägagångssätt, planering. Diskutera utifrån exempel-experiment med bildinnehåll hos Facebook-poster. Ögonrörelsemätning för visuell uppmärksamhet, Likert-skalor för attitydmätning. Giltighet och tillförlitlighet hos alla mätvariabler, beroende variabler som används i studien. Återkoppla till pilottest.

### 7.3.5 Rapportering av mätinstrument {#sub7.3.5}

Rapportering. På engelska kallas detta avsnitt ofta för \"apparatus\". Exempel på hur detta skulle kunna formuleras i ett artikelmanuskript. Utgår från exempel-experimentet.

## 7.4 Experimentella villkor  {#sec7.4}

\[10 sidor\]

Ett typiskt experiment består ofta av ett kontrollvillkor och ett eller flera experimentella villkor. Ett kontrollvillkor refererar till ett slags naturligt normaltillstånd, som kännetecknas av att deltagaren **inte** genomgår någon form av behandling, eller exponeras för någon form av manipulation. Experimentella villkor å andra sidan betyder att försöksdeltagaren genomgår just en sådan behandling (t.ex. genom att inta en verksam medicinsk substans) eller utsätts för en manipulation (t.ex. genom exponering för en viss nivå av belysning). I ett enkelt experiment förekommer endast dessa två tillstånd, vilket kan beskrivas med en s.k. oberoende variabel, där frånvaron av behandling (kontrollvillkor) exempelvis representeras av symbolen \"0\", medan förekomsten av en behandling (behandlingsvillkor) representeras av symbolen \"1\". I mer invecklade experiment kan det förekomma kombinationer av flera behandlingar (t.ex. intag av medicin **och** exponering för belysning) som dessutom utdelas i flera olika nivåer (t.ex. \"ingen dos\", \"låg dos\", och \"hög dos\"). Mer om detta längre fram.

Genom att mäta försöksdeltagarnas responser med hjälp av någon relevant beroende variabel (t.ex. blodtryck) under både kontrollvillkor och experimentella villkor, undersöks därefter eventuella skillnader mellan dessa villkor (dvs. effekter av behandling jämfört med normaltillståndet). På engelska kallas sådana villkor ofta för \"conditions\" eller \"treatments\". I detta sammanhang är det viktigt att betänka att kontrollvillkor och experimentella villkor (\"conditions\") bör betraktas som abstrakta begrepp, vilka sedan behöver konkretiseras i form av faktiska, reella behandlingar (\"treatments\"), ofta med hjälp av teknisk utrustning och laboratoriemateriel, samt en standardiserad procedur för att utdela dessa behandlingar. Denna process, i vilken abstrakta villkor implementeras som någon form av konkreta behandlingar, kallas ibland för operationalisering (se tidigare avsnitt 6.2). Inom ett experiment är det även vanligt att behandlingar upprepas ett visst antal gånger, vilket kallas för försök, eller på engelska \"trials\" (se experimentdesign nedan).

### 7.4.1 Kontrollvillkor och behandlingsvillkor {#sub7.4.1}

Låt oss återvända till bokens tänka exempel-experiment för att utveckla och konkretisera resonemanget kring experimentella villkor. Som vi har sagt tidigare, kräver den enklaste formen av experiment en kontrast mellan att deltagaren genomgår en behandling eller att de inte gör det. Att **inte** genomgå en behandling kallas för ett kontrollvillkor, och dessa deltagare sägs därmed tillhöra kontrollgruppen. I fallet med medicinsk forskning kan detta villkor tyckas ganska uppenbart: det kan bestå i att en grupp deltagare inte tar ett läkemedel. Men i ett samhällsvetenskapligt experiment kan det vara betydligt svårare att definiera vad som är ett kontrollvillkor.

I vårt Facebook-experiment exponeras deltagare för två olika typer av bildinnehåll \-- antingen presenteras en Facebook-post med en bild på en auktoritetsperson, eller en bild på en neutral person. Vilket av dessa två bildvillkor utgör då kontrollvillkoret? Båda grupperna av försöksdeltagare exponeras ju för någon form av bild, och omvänt, ingen av grupperna får titta på Facebook-posten utan bild. För att resonera om kontrollvillkoret i detta exempel kan vi börja med att tänka oss samtliga bilder på personer som existerar på Facebook. Därefter låter vi en slumpmässigt utvald Facebook-användare titta på tio slumpmässigt utvalda bilder ur samlingen av alla bilder. Slutligen ställer vi oss frågan: kommer denna användare se fler bilder på okända, och i den meningen neutrala personer, eller kommer användaren att se fler bilder som han eller hon relaterar till som auktoritetspersoner? Statistiskt sett skulle vi nog säga att de flesta bilderna användaren ser troligen kommer föreställa okända och därmed neutrala personer, och därigenom kan vi resonera att Facebook-bilder med neutrala personer bör utgöra vårt kontrollvillkor. Mer generellt uttryckt är det vanligt att kontrollvillkoret får motsvara det typiska fallet, medan behandlingsvillkoret innehåller en otypisk manipulering av något slag.

Behandlingsvillkoret består därmed i att visa en Facebook-post med en bild föreställande en auktoritetsperson. För att ta ett konkret exempel kan vi anta att personen Leif G.W. Persson för många användare utgör en auktoritet i samband med Facebook-poster gällande kriminalitet. Att presentera en Facebook-post om kriminalitet tillsammans med en bild på Leif G.W. Persson skulle alltså utgöra behandlingsvillkoret i vårt experiment, medan att presentera samma Facebook-post med en neutral och okänd person skulle utgöra kontrollvillkoret. Det är mycket viktigt att betona att Facebook-posten (om kriminalitet) är samma i båda villkoren, medan bildinnehållet (auktoritetsperson, neutral person) varieras.

Detta innebär att så mycket som möjligt i Facebook-posten hålls konstant över båda villkoren, medan en enda aspekt varieras. Detta är helt centralt för experimentell metod, eftersom det innebär att om vi uppmäter skillnader i de beroende variablerna (visuell uppmärksamhet och upplevd trovärdighet) så kan dessa skillnader mer sannolikt härledas till själva bildvillkoren och inget annat. Denna härledning blir betydligt svårare eller kanske till och med omöjlig att göra om vi samtidig varierar andra egenskaper hos Facebook-posten, t.ex. antal gillningar och rubriktext. I en undersökning är alltså behandlingsvillkor och kontrollvillkor lika viktiga, och allt annat utom själva villkoren bör hållas konstant.

använder behandlingsvillkor i rubriken till detta stycke mest för att skapa en tydlig kontrast till kontrollvillkor i föregående avsnitt. Behandlingsvillkor benämns nämligen ofta som experimentella villkor, och fortsättningsvis kommer vi huvudsakligen använda denna beteckning.

### 7.4.2 Oberoende variabler {#sub7.4.2}

Oberoende variabler hänger konceptuellt samman med experimentella villkor, eller behandlingsvillkor, på så sätt att oberoende variabler används för att operationalisera experimentella villkor. Här påminner vi oss som hastigast om att operationalisering hittills definierats som att göra ett koncept mätbart. Vi kan nu utveckla och konkretisera denna definition genom att säga att en oberoende variabel registrerar varje gång en försöksdeltagare genomgår kontrollvillkoret eller behandlingsvillkoret inom en undersökning. Denna registrering görs i praktiken ofta med hjälp av ett datorprogram för hantering av tabelldata (registerdata) såsom Microsoft Excel, där första kolumnen kan tänkas innehålla alla deltagare i undersökningen (t.ex. deltagarnummer \"1\", \"2\", \"3\", osv), medan den andra kolumnen registrerar om respektive deltagare exponerats för kontrollvillkoret (\"Kontroll\") eller behandlingsvillkoret (\"Behandling\"). Med hjälp av denna uppställning kan alltså en enda oberoende variabel (kolumnen \"Villkor\" i figuren nedan) användas för att representera både kontrollvillkor och behandlingsvillkor. Slutligen används en kolumn för att registrera eller uppmäta den beroende variabeln i undersökningen (kolumnen \"Utfall\"), vilket behandlades i föregående kapitel.

Tabell 1.1 Det här är tabellrubriken

  Deltagare   Villkor      Utfall
  ----------- ------------ ------------
  1           Kontroll     Oförändrat
  2           Behandling   Positivt
  3           Kontroll     Oförändrat
  4           Behandling   Oförändrat
  \...        \...         \...

I exempel-experimentet som beskrivs i denna bok, skulle kolumnen \"Villkor\" i figuren ovan kanske innehålla värdena \"Neutral person\" (för kontrollvillkoret) eller \"Auktoritetsperson\" (för behandlingsvillkoret), beroende på vilken typ av Facebook-post respektive deltagare exponerats för i undersökningen. I detta fall blir både kategoriska variabler. Skulle finnas två utfallsvariabler, nämligen visuell uppmärksamhet mätt i sekunder, samt upplevd trovärdighet mätt på en skala från 1-7.

Experimentella villkor är starkt kopplade till oberoende variabler. Inom den experimentella forskningen syftar begreppet på klargörandet av vilka mätvariabler som uppmäts i en undersökning (oftast en eller flera **beroende variabler** kopplade till deltagarnas responser), samt vilka variabler som varieras eller manipuleras i undersökningen (oftast en eller flera **oberoende variabler** kopplade till undersökningens behandlingar). En undersökning skulle till exempel kunna fokusera på effekten av olika typer av lärarledd feedback på studenters studieresultat (dock inte inlärningsförmåga). I denna situation representerar lärares feedback den oberoende variabeln, medan något mått på studenters inlärning kan representera den beroende variabeln. Förutom att klargöra dessa två kategorier av variabler, så bör den experimentella designen också specificera de olika värden eller nivåer som de oberoende variablerna kan anta. I exemplet med inlärning ovan kan man tänka sig att variabeln \"lärares feedback\" kan anta värden som varierar mellan \"positiv\", \"negativ\" eller \"neutral\" feedback. I detta fall skulle man säga att den oberoende variabeln feedback har tre olika nivåer eller \"levels\" på engelska (dessa nivåer kan vidare betraktas som mer kategoriska eller mer kontinuerliga till sin natur, se variabler kapitel xx). Här är det viktigt att tydliggöra att dessa nivåer på den oberoende variabeln är den operationaliserade versionen av de experimentella villkor vi diskuterade i kapitlet innan.

En viss uppgift eller instruktion kan också vara ett experimentellt villkor. I sådana fall kontrasteras ofta denna uppgift mot ett kontrollvillkor där ingen uppgift eller instruktion förekommer (t.ex. fri interaktion)

Till skillnad från beroende variabler, ofta kategoriska, faktorer med nivåer.

### 7.4.3 Kontrollvariabler {#sub7.4.3}

En annan faktor som har stor betydelse i samband med urvalet av

### 7.4.4 Utrustning och materiel {#sub7.4.4}

Implementation (operationalisering) av abstrakt villkor till konkret behandling. Kan vara intag av en medicinsk substans eller exponering för ett visuellt stimuli (material). Utrustning som används för att distribuera materiel. Efter att man avhandlat försöksdeltagare och eventuella pilottest, är det vanligt att man i en journalartikel övergår till att diskutera den tekniska utrustning och apparatur som använts i samband med genomförandet av ett experiment.

Generellt: Utrustning som används för att på ett kontrollerat sätt generera eller presentera ett stimuli eller en behandling. Teknisk utrustning som används för att genomföra ett experiment, datorer som används för att spela in data, datorskärm som används för att presentera stimuli (Facebook-artiklar). Presenteras som HTML-sidor I webbläsaren. Synonymt med materiel (engelska materials)?

Material, Stimulikonstruktion. Här förklarar vi exakt vad det är vi manipulerar eller varierar I experimentet, samt I vilka nivåer en egenskap manipuleras. I exemplet med Facebook-artiklar varierar vi bildinnehållet i två nivåer, \"neutral person\" och \"auktoritetsperson\". Vi beskriver också hur vi säkerställt att denna skillnad bildinnehåll är objektiv och uppfattas på samma sätt av olika delagare (intercoder reliability). Vi varierar inte antalet \"likes\" som respektive Facebook-artikel har fått, eller vilken källa som visas. Vad varieras, vad hålls konstant? Full factorial design may also be called a fully crossed design. Se följande stycke om experimentdesign.

### 7.4.5 Planering av experimentella villkor {#sub7.4.5}

Tillvägagångssätt, planering. Sammanfattning av avsnitt 7.4. Diskutera utifrån exempel-experiment med bildinnehåll hos Facebook-poster. Giltighet och tillförlitlighet hos alla förklaringsvariabler, oberoende variabler som används i studien. Återkoppla till betydelsen av pilottest.

### 7.4.6 Rapportering av experimentella villkor {#sub7.4.6}

Rapportering - exempel på hur detta skulle kunna formuleras i ett manuskript

## 7.5 Experimentell design  {#sec7.5}

\[10 sidor\]

Design är ett ganska svårdefinierat begrepp, vars innebörd handlar om att på ett överskådligt sätt sammanfatta strukturen och planen hos en vetenskaplig undersökning (på svenska används ibland \"upplägg\" eller \"planering\" som synonymer till design). Man kan säga att begreppet experimentell design har två centrala aspekter: den första är kopplad till att beskriva och specificera de beroende och oberoende variablerna som ingår en undersökning, medan den andra centrala aspekten är kopplad till att beskriva hur deltagarna i en undersökning exponeras för de experimentella villkor som omfattas av de oberoende variablerna (dvs hur behandlingar eller \"trials\" är distribuerade inom en experimentell studie). I det följande ska vi börja med att diskutera experimentell design i relation till oberoende variabler, vilka vi även refererar till som behandlingsvariabler i denna bok.

För att få en bättre förståelse av begreppet experimentdesign börjar vi med ett exempel från den medicinska forskningen. En epidemiologisk forskare bestämmer sig för att testa ett nytt vaccin som den tagit fram. För att undersöka detta bestämmer sig forskaren (i vanlig ordning :) för att rekrytera försöksdeltagare som delas in i två grupper, där en grupp får en overksam spruta med saltvattenlösning, och deltagare i den andra gruppen får en spruta med det nya vaccinet. Vi säger därför att detta experiment har en **mellangruppsdesign**, eftersom effekten av den oberoende variabeln (vatten vs. vaccin) mäts och jämförs mellan två likvärdiga grupper av deltagare. Som tumregel kan man säga att en enklare experimentdesign är ofta att föredra framför en mer komplicerad design. Orsaken till detta är att en enkel design ofta genererar tydligare resultat som är enklare att tolka. Enklare experimentella designer består ofta bara av en enda oberoende variabel som kan vara antingen kontinuerlig eller diskret (). När man designar ett experiment försöker man ofta passa på att

Även om enkla experiment är idealet så finns det flera situationer där exempelvis en mellangruppsdesign inte riktigt räcker till. En sådan situation kan inträffa om den uppmätta effekten av en behandling på en viss utfallsvariabel är relativt liten jämfört med kontrollvillkoret. I sådana situationer riskerar alltså en eventuell effekt av behandlingen att drunkna i bakgrundsbruset från andra orsaksfaktorer. En annan situation där en enkel mellangruppsdesign kan vara otillräckligt är om det naturligt förekommer stora individuella skillnader mellan deltagarna inom respektive försöksgrupp med avseende på utfallsvariabeln. Gemensamt för båda dessa problematiska situationer är alltså att den förväntade effekten av behandlingen är liten i relation till andra omgivande bruskällor (i överförd bemärkelse används ibland det engelska uttrycket \"low signal-to-noise ratio\"), och att det därför föreligger en risk för typ I- och typ II-fel (false positives respektive false negatives).

Just detta är ofta fallet i samhällsvetenskapliga undersökningar, där det är vanligt att kvantitativa data samlas in genom självrapporterade enkätsvar som ytterst är beroende av varje deltagares vilja och förmåga att svara uppriktigt, vilket skapar stor individuell variation. Här krävs alltså experimentdesigner som är mer robusta i på grund av brusiga datainsamlingar innehållande flera potentiella felkällor. En lösning på detta problem är så kallad **inomgruppsdesign**, vilket vi ska diskutera längre fram i detta kapitel. Den tydligaste skillnaden gentemot mellangruppsdesign är dock att denna typ av experiment exponerar varje deltagare för både kontrollvillkor och behandlingsvillkor, samt att denna exponering kan upprepas flera gånger för varje deltagare. Av naturliga skäl är detta experimentella upplägg många gånger svårt eller omöjligt att genomföra inom den medicinska forskningen, eftersom försöksdeltagare inte både kan ges en placebotablett och en verksam medicin vid samma tillfälle.

### 7.5.1 Instruktioner och uppgifter {#sub7.5.1}

Många samhällsvetenskapliga experiment brukar börja med en instruktion som ges till varje deltagare för att förklara vad som kommer hända, vilken uppgift som ska lösas, samt vad vi som forskare mäter hos deltagaren (dock nämner vi inte vad som har manipulerats i experimentets, eftersom deltagaren bör hållas omedveten om detta). Dessa instruktioner är i sig en viktig aspekt av experimentet, eftersom forskaren därigenom försöker uppnå en standardiserad situation där alla deltagare uppfattar experimentet på samma sätt, för att på så sätt öka validiteten och reliabiliteten hos insamlade data.

Men vi skulle också kunna använda instruktioner för att ge olika uppgifter till två grupper av deltagare, medan resten av experimentet är identiskt för båda grupperna, och i så fall utgör själva uppgiften experimentets manipulation. Låt oss ta ett konkret exempel i form av en undersökning där varje deltagare får titta på ett antal bilder som visas en i taget på en datorskärm samtidigt som vi spelar in deltagarens blickbeteende. Hälften av deltagarna får instruktionen att titta fritt på bilderna (\"free-viewing\"), medan den andra hälften får instruktionen att försöka hitta ett specifikt objekt i varje bild (\"visual search\"). Genom denna variation i instruktioner har vi skapat ett experiment med mellangruppsdesign, innehållande ett kontrollvillkor (titta fritt), samt ett behandlingsvillkor (hitta objekt). Vi kan därefter undersöka om blickbeteende mellan dessa grupper systematiskt skiljer sig åt på det sätt vi antagit i våra hypoteser.

Exemplet ovan handlar om en specifik användning av instruktioner för att generera ett experimentellt villkor. Mer generellt kan man säga att det ofta är fördelaktigt att ge deltagare någon form av uppgift i samband med ett experiment, eftersom man därigenom minskar variationen i hur deltagare interagerar med experimentets villkor. Mindre variation gör i sin tur att vi får större möjligheter att upptäcka statistiska skillnader mellan villkoren med avseende på någon utfallsvariabel. En uppgift av något slag gör deltagarna mer fokuserade. Dessutom innebär en uppgiftsstyrd eller målorienterad experimentdesign (engelska \"task-oriented\" eller \"goal-directed\") att vi som forskare får möjlighet att mäta uppgiftsprestation (engelska \"task performance\"), vilket ofta är en användbar variabel.

### 7.5.2 Randomisering och balansering {#sub7.5.2}

Vi har hittills diskuterat de individer som deltar i experiment (7.2 Försöksdeltagare), de beroende variabler experimentet undersöker hos deltagarna (7.3 Mätinstrument), samt de behandlingar som dessa individer genomgår (7.4 Experimentella villkor). När vi nu fortsätter med att diskutera experimentdesign (7.5), är förmodligen en av de viktigaste aspekterna begreppet \"randomisering\" (ref, Fisher). Randomisering är så centralt att det ibland tas för givet inom den experimentella forskningen. Dock kan detta utgöra ett av de mer krävande momenten i att designa ett experiment för studenter och yngre forskare, eftersom randomisering ofta kräver grundläggande kunskaper i programmering för att realiseras. Bristfällig randomisering i experimentdesignen är ofta något som skapar problem när man analyserar effekten av experimentella villkor på en eller flera utfallsvariabler, och försöker dra slutsatser om statistiskt säkerställda effekter.

Randomisering (på engelska \"random assignment\") innebär i grund och botten att experimentledaren låter slumpen avgöra vilket experimentellt villkor (eller behandling) varje deltagare genomgår. I det enklaste fallet, där experimentet endast består av ett kontrollvillkor samt ett behandlingsvillkor, kan vi tänka oss att experimentledare låter varje deltagare singla slant, och beroende på utfallet (krona eller klave) tilldelar deltagaren ett av de två villkoren. Med tillräckligt många deltagare förutsäger slumpens lagar att fördelningen mellan två experimentella villkor kommer bli ungefär 50%, dvs. att hälften av deltagarna exponeras för kontrollvillkoret, och den andra hälften genomgår behandlingsvillkoret. Det viktigaste syftet med randomisering är dock att försäkra oss om att experimentledaren inte kan påverka experimentets genomförande, och att varje deltagare tilldelas ett villkor på ett sätt som är oberoende av vilket villkor alla andra deltagare tilldelas.

Dessutom kan randomiseringen användas för att hålla försöksdeltagaren i ovisshet om vilket behandlingsvillkor den exponerats för. Denna experimentdesign är vanlig i medicinska studier, och kallas då för en blind-studie (på engelska \"blinded experiment\"), dvs. varje försöksdeltagare hålls omedveten om den får ett sockerpiller (kontrollvillkor) eller en verksam substans (behandlingsvillkor). Tanken med denna design är att reducera effekten av deltagarens förväntningar, den så kallade placebo-effekten, för att därigenom erhålla mer tillförlitliga resultat. Inom den medicinska forskningen är det också vanligt att gå ett steg längre, och därigenom även hålla försöksledaren omedveten om vilken behandling en viss deltagare tilldelas. I sådana fall talar man om en dubbel blind-studie (på engelska \"double-blind study\"). Tanken med att hålla försöksdeltagaren omedveten om vilket experimentellt villkor den exponeras för, är besläktad med tanken att hålla deltagaren omedveten eller \"naiv\" om syftet med experimentet, dvs. vilka mätvariabler och behandlingsvariabler som används inom experimentet (jfr. 7.2.4). Gemensamt för dessa designprinciper är syftet att reducera bias och öka tillförlitligheten hos studien.

Återgår vi till att diskutera randomisering mer specifikt, så kan vi konstatera att denna designprincip är ganska enkel och intuitiv så länge en studie bara kontrasterar två villkor, och där varje deltagare endast exponeras för ett av dessa villkor en gång. Denna så kallade mellangruppsdesign (vilken vi diskuterar mer utförligt i nästa avsnitt) fungerar ofta bra för enkla studier, men inom samhällsvetenskap och humanvetenskap kan det ibland krävas något mer avancerade experimentdesigner, vilket i sin tur kräver andra former av randomisering. Detta kan exempelvis inträffa om experimentet innefattar ett kontrollvillkor och två eller flera behandlingsvillkor, eller om varje deltagare genomgår flera villkor, eller om experimentet innehåller någon kombination av dessa situationer. Betänk experimentdesignen som visas i tabellen nedan, där varje deltager genomgår kontrollvillkoret samt två olika behandlingsvillkor.

Tabell 1.1 Det här är tabellrubriken

  Deltagare        Stimulus 1     Stimulus 2     Stimulus 3     
  ---------------- -------------- -------------- -------------- --
  Deltagare 1 \>   Kontroll       Behandling A   Behandling B   
  Deltagare 2 \>   Behandling A   Kontroll       Behandling B   
  Deltagare 3 \>   Behandling B   Behandling A   Kontroll       
  \...                                                          

I denna situation skulle vi som forskare kunna välja att låta varje deltagare först genomgå villkoret Kontroll, följt av Behandling A och Behandling B. Denna design vore kanske den enklaste att implementera, men den kan vara problematisk på andra sätt. För att konkretisera denna situation kan vi tänka oss ett experiment där varje deltagare får betrakta tre ansiktsbilder i följd. Den första bilden visar ett ansikte med neutral min (Kontroll), medan det andra ansiktet visar en ledsen min (Behandling A), och det tredje ansiktet visar en glad min (Behandling B). För varje ansikte försöksdeltagaren får betrakta, instrueras den att ange på en skala hur glad eller ledsen personen på bilden är. Skalan går från mycket ledsen (-10) till mycket glad (+10).

Problemet med denna experimentdesign, där villkoren inte randomiseras, inträffar om vi tänker oss att varje villkor i någon grad influerar nästkommande villkor (jfr. begreppet \"priming\"). Detta skulle kunna inträffa om deltagarna, efter att ha betraktat det neutrala ansiktet, upplever att det ledsna ansiktet är något mindre ledset än om det ledsna ansiktet hade betraktats först. På samma sätt skulle deltagarna kunna uppleva att det glada ansiktet är något mindre glatt efter att de betraktat det ledsna ansiktet. Denna typ av systematiska ordningseffekter (på engelska \"order effects\") är svåra att undvika helt, men med hjälp av randomisering kan vi åtminstone försöka minimera dem.

I ansiktsstudien ovan skulle vi kunna lösa randomiseringen på åtminstone två olika sätt. Det första sättet vore att ge varje bild 1/3 chans att presenteras som första, andra och tredje villkor. Detta kallas för randomisering utan ersättning (\"randomization without replacement\"). Det andra sättet vore att göra en lista med alla de sex möjliga ordningsföljder i vilka man kan presentera tre villkor, och sedan presentera villkoren enligt dessa ordningsföljder för de sex första deltagarna. Därefter upprepas ordningsföljderna för nästa sex deltagare. Denna metod kallas för \"latin square\", och innebär idealiskt att vi skulle behöva ett totalt antal deltagare i studien som är en multipel av sex (dvs. 12, 18, 24, osv.) för att designen ska vara helt balanserad. Randomisering är alltså viktigt om man kan misstänka att experimentella villkor skapar ordningseffekter, vilket som regel antas vara fallet i humanvetenskapliga och samhällsvetenskapliga studier. Mest kritiskt i studier med inomgruppsdesign och upprepade villkor.

### 7.5.3 Mellangruppsdesign {#sub7.5.3}

Den enklaste formen av experimentell design (och därmed ofta den tydligaste) kan antagligen härledas från den medicinska forskningen. I denna experimentdesign ingår två stycken grupper av försöksdeltagare som i möjligaste mån är jämförbara (eller \"matchade\") vad gäller ett antal olika demografiska variabler, såsom ålder, kön och hälsotillstånd mm. Varje deltagargrupp blir sedan slumpmässigt tilldelad en behandling (t.ex. en ny blodtryckssänkande medicin som testas) eller ingen behandling (t.ex. ett sockerpiller som antas vara verkningslöst). Efter att varje försöksdeltagare genomgått en av dessa två behandlingar (eller experimentella villkor) undersöker experimentledaren effekten av respektive behandling genom att uppmäta värdet på en utfallsvariabel kopplad till deltagaren (t.ex. blodtryck). Om den medicinska behandlingen haft en effekt jämfört med sockerpiller bör man finna en tydlig kontrast mellan deltagargrupperna (t.ex. lägre genomsnittligt blodtryck).

Ett typisk kommunikationsvetenskapligt exemplet på mellangruppsdesign är ett så kallat AB-test. Expandera.

Tabell 1.1 Det här är tabellrubriken

  Tabellhuvud    Tabellhuvud   Tabellhuvud                   
  -------------- ------------- -------------- -------------- --
  Villkor \>     Kontroll      Behandling A   Behandling B   
  Deltagare \>   Deltagare 1   Deltagare 2    Deltagare 3    
  \...           Deltagare 4   Deltagare 5    Deltagare 6    

Låt oss i det följande återvända till vårt tänka exempel-experiment, där syftet är att undersöka hur medieanvändares interaktion med (ögonrörelsemätning), och attityder till (survey-skalor), Facebook-poster påverkas av om posten innehåller en bild på en auktoritetperson alternativt en bild på en neutral person. För att testa detta experimentellt behöver vi först välja ut en Facebook-post som vi kan använda som stimuli. Vi kan anta att vi väljer ut en post på temat brottlighet i Sverige. Därefter behöver vi välja två bilder som kommer utgöra experimentets behandlingar eller villkor. Vi antar att kriminologen Leif G.W. Persson kan anses vara en auktoritetsperson inom området brottslighet, och använder en bild på honom för att konstruera Facebook-postens behandlingsvillkor. Därefter väljer vi en bild på en neutral person, och använder denna bild för att konstruera vårt kontrollvillkor.

Om vi nu skulle välja att genomföra detta experiment med mellangruppsdesign, skulle det innebära att vi började rekrytera ett hundratal försökspersoner som är någorlunda lika i demografiskt avseende, och någorlunda representativa för den population vi ämnar undersöka. Därefter skulle vi låta deltagarna interagera med Facebook-posten på en datorskärm medan vi spelade in deras ögonrörelser, och efter att ha läst posten skulle deltagarna få markera på en 7-gradig likert-skala hur pass trovärdig de upplevde att Facebook-posten i sin helhet var. Hälften av deltagarna skulle därvidlag få läsa posten i kontrollvillkoret, medan den andra häften fick läsa posten i behandlingsvillkoret. Randomiseringen skulle kunna lösas så att villkoren slumpades fram med 50% sannolikhet vardera, eller genom att varannan deltagare genomgick kontrollvillkoret, och varannan behandlingsvillkoret.

\- ibland enda möjliga design, introducerar dock mätfel på grund av individuella skillnader, dvs deltagargrupperna kan aldrig bli helt \"matchade\" i alla avseenden - En deltagargrupp per villkor (between-subjects design) \"oberoende grupper\" - upprepade behandlingar (repeated measures) omvandlar studien till inomgruppsdesign - effekten kontrasteras mellan deltagare - två behandlingar + kontroll, kräver fler deltagare, dvs designen skalar inte upp så bra - övergång till nästa avsnitt: sammanfatta svagheterna med mellangruppsdesign

### 7.5.4 Inomgruppsdesign {#sub7.5.4}

Ett sätt att åtgärda en del av svagheterna med mellangruppsdesign är att istället använda experiment med inomgruppsdesign, ibland även kallat inompersonsdesign, eller på engelska \"within-subjects design\". Det främsta kännetecknet för denna experimentdesign är att varje deltagare ingår i studiens alla villkor, både kontrollvillkor och experimentella villkor. Detta innebär således att varje försöksdeltagare jämförs med sig själv mellan undersökningens villkor. En betydande fördel med en sådan experimentdesign är att man därigenom kan kontrollera för individuella skillnader mellan deltagare, och att effekten av denna bruskälla därför blir mindre när man kontrasterar mätningar av någon responsvariabel mellan experimentella villkor (variansen inom varje villkor blir mindre). Man kan således argumentera för att en inomgruppsdesign är mer rättvis än en mellangruppsdesign i och med att varje deltagare exponeras för alla manipulationer som undersökningen består av. Detta kan vara fördelaktigt ur etisk synpunkt. En annan fördel med denna design är att den skalar upp bättre om man skulle tillföra fler nivåer på en oberoende variabel, dvs. om man skulle lägga till en behandling. I sådana situationer behöver man inte rekrytera en grupp med nya försöksdeltagare (vilket vore fallet i en mellangruppsdesign), utan samma deltagare exponeras bara för ytterligare ett behandlingsvillkor. En möjlig nackdel med detta är att experimentet tar längre tid för varje deltagare, när den ska delta i fler villkor.

\- effekten kontrasteras inom varje deltagare, dvs inga deltagargrupper - Alla deltagare genomgår alla villkor (within-subjects design) \"beroende grupper\", inompersonsdesign - lämpligare vid beteendevetenskapliga studier - variables and level of variables (e.g. 2x3 between-subjects design) - Något om Blandad design (mixed design).

Tabell 1.1 Det här är tabellrubriken

  Tabellhuvud    Tabellhuvud   Tabellhuvud                   
  -------------- ------------- -------------- -------------- --
  Villkor \>     Kontroll      Behandling A   Behandling B   
  Deltagare \>   Deltagare 1   Deltagare 1    Deltagare 1    
  \...           Deltagare 2   Deltagare 2    Deltagare 2    

Diskutera expempel experiment med Facebook-poster enligt ett upplägg med inomgruppsdesign.

### 7.5.5 Upprepade villkor {#sub7.5.5}

När vi i föregående avsnitt diskuterat mellangruppsdesign och inomgruppsdesign har vi avstått från att ta upp frågan om upprepade villkor. Underförstått har vi då antagit att varje deltagare exponeras för ett villkor (mellangruppsdesign) eller alla villkor (inomgruppsdesign) endast en gång. I vissa typer av experiment är detta ett rimligt antagande; i medicinska studier förväntar vi oss kanske att varje deltagare genomgår ett kontrollvillkor i form av sockerpiller, eller ett experimentellt villkor i form av ett läkemedel, endast en gång. Man skulle dock kunna tänka sig att dessa behandlingar upprepas ett antal gånger med samma försöksdeltagare och med en viss tidsperiods mellanrum. Tanken med att upprepa villkoren är att de uppmätta resultaten sammantaget ska ge en mer rättvis bild av effekten hos varje deltagare än om endast en mätning gjordes. I sådana fall skulle man kalla detta för

\- formuleringen \"within-subjects repeated measures design\"

Tabell 1.1 Det här är tabellrubriken

  Tabellhuvud      Tabellhuvud   Tabellhuvud                   
  ---------------- ------------- -------------- -------------- --
  Deltagare 1 \>   Kontroll      Behandling A   Behandling B   
  Deltagare 1 \>   Kontroll      Behandling A   Behandling B   
  Deltagare 2 \>   Kontroll      Behandling A   Behandling B   
  \...                                                         

Diskutera expempel experiment med Facebook-poster enligt ett upplägg med mellangruppsdesign och upprepade villkor.

### 7.5.6 Faktoriell design {#sub7.5.6}

Två eller fler oberoende variabler (faktorer), med två eller fler diskreta nivåer (eng. \"levels\") på varje faktor. 3x2 faktoriell design. Tillåter att effekten av alla nivåer på varje enskild faktor testas, liksom effekten av alla kombinationer av faktorer (interaktioner). Används ofta inom naturvetenskapliga sammanhang, t.ex. materialtestning. \"Fully crossed design\" - variables and level of variables (e.g. 2x3 between-subjects design)

Tabell 7.5.5 Faktoriell experimentdesign

  Tabellhuvud         Tabellhuvud         Tabellhuvud                             
  ------------------- ------------------- ------------------- ------------------- --
                      Faktor A (nivå 0)   Faktor A (nivå 1)   Faktor A (nivå 2)   
  Faktor B (nivå 0)   Kontroll A0/B0      Behandling A1/B0    Behandling A2/B0    
  Faktor B (nivå 1)   Behandling A0/B1    Behandling A1/B1    Behandling A2/B1    

### 7.5.7 Kvasi-experimentell design {#sub7.5.7}

T.ex. undersökning av effekterna av medborgarlön? Kontrastera med naturliga experiment? Ett sätt att tänka kring oberoende variabler är att de representerar experimentets utfallsvariabler. En annan faktor som har stor betydelse i samband med urvalet av.. lacks random assignment, naturliga exp del 1

### 7.5.8 Planering av experimentell design {#sub7.5.8}

Håll designen så enkel som möjligt för att underlätta tolkningen av resultat. Helst inte mer än 2x2 design. - diskutera utifrån exempel-experiment med bildinnehåll hos Facebook-poster

bild kommer ovan

### 7.5.9 Rapportering av experimentell design {#sub7.5.9}

Håll designen så enkel som möjligt för att underlätta tolkningen av resultat. Helst inte mer än 2x2 design.

## 7.6 Procedur  {#sec7.6}

\[10 sidor\]

\- reliabilitet, standardisering, alla deltagare genomgår samma procedur, externa faktorer hålls så konstanta som möjligt - **Instruktion**, **uppgift**, dvs läs Facebook-artiklarna och bedöm sedan trovärdighet på en ordinal skala. Alternativt kan den skarpa uppgiften döljas, och istället ger man en skenuppgift till deltagarna för att hålla dem naiva om experimentets syfte och undvika bias

## 7.7 Dataanalys  {#sec7.7}

\[5 sidor\]

Beräkning av beroende och oberoende variabler - aggregering, summativt index
